Bump Haskell CI to GHC 9.10.1

diff --git a/.github/workflows/haskell-ci.yml b/.github/workflows/haskell-ci.yml
--- a/.github/workflows/haskell-ci.yml
+++ b/.github/workflows/haskell-ci.yml
@@ -8,9 +8,9 @@
 #
 # For more information, see https://github.com/andreasabel/haskell-ci
 #
-# version: 0.17.20231012
+# version: 0.19.20240517
 #
-# REGENDATA ("0.17.20231012",["github","cabal.project"])
+# REGENDATA ("0.19.20240517",["github","cabal.project"])
 #
 name: Haskell-CI
 on:
@@ -27,24 +27,29 @@ jobs:
     timeout-minutes:
       60
     container:
-      image: buildpack-deps:focal
+      image: buildpack-deps:jammy
     continue-on-error: ${{ matrix.allow-failure }}
     strategy:
       matrix:
         include:
-          - compiler: ghc-9.8.1
+          - compiler: ghc-9.10.1
             compilerKind: ghc
-            compilerVersion: 9.8.1
+            compilerVersion: 9.10.1
             setup-method: ghcup
             allow-failure: false
-          - compiler: ghc-9.6.3
+          - compiler: ghc-9.8.2
             compilerKind: ghc
-            compilerVersion: 9.6.3
+            compilerVersion: 9.8.2
             setup-method: ghcup
             allow-failure: false
-          - compiler: ghc-9.4.7
+          - compiler: ghc-9.6.5
             compilerKind: ghc
-            compilerVersion: 9.4.7
+            compilerVersion: 9.6.5
+            setup-method: ghcup
+            allow-failure: false
+          - compiler: ghc-9.4.8
+            compilerKind: ghc
+            compilerVersion: 9.4.8
             setup-method: ghcup
             allow-failure: false
           - compiler: ghc-9.2.8
@@ -84,11 +89,10 @@ jobs:
           apt-get update
           apt-get install -y --no-install-recommends gnupg ca-certificates dirmngr curl git software-properties-common libtinfo5 libnuma-dev
           mkdir -p "$HOME/.ghcup/bin"
-          curl -sL https://downloads.haskell.org/ghcup/0.1.19.5/x86_64-linux-ghcup-0.1.19.5 > "$HOME/.ghcup/bin/ghcup"
+          curl -sL https://downloads.haskell.org/ghcup/0.1.20.0/x86_64-linux-ghcup-0.1.20.0 > "$HOME/.ghcup/bin/ghcup"
           chmod a+x "$HOME/.ghcup/bin/ghcup"
-          "$HOME/.ghcup/bin/ghcup" config add-release-channel https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-prereleases-0.0.7.yaml;
           "$HOME/.ghcup/bin/ghcup" install ghc "$HCVER" || (cat "$HOME"/.ghcup/logs/*.* && false)
-          "$HOME/.ghcup/bin/ghcup" install cabal 3.10.1.0 || (cat "$HOME"/.ghcup/logs/*.* && false)
+          "$HOME/.ghcup/bin/ghcup" install cabal 3.10.3.0 || (cat "$HOME"/.ghcup/logs/*.* && false)
         env:
           HCKIND: ${{ matrix.compilerKind }}
           HCNAME: ${{ matrix.compiler }}
@@ -106,7 +110,7 @@ jobs:
           echo "HC=$HC" >> "$GITHUB_ENV"
           echo "HCPKG=$HCPKG" >> "$GITHUB_ENV"
           echo "HADDOCK=$HADDOCK" >> "$GITHUB_ENV"
-          echo "CABAL=$HOME/.ghcup/bin/cabal-3.10.1.0 -vnormal+nowrap" >> "$GITHUB_ENV"
+          echo "CABAL=$HOME/.ghcup/bin/cabal-3.10.3.0 -vnormal+nowrap" >> "$GITHUB_ENV"
           HCNUMVER=$(${HC} --numeric-version|perl -ne '/^(\d+)\.(\d+)\.(\d+)(\.(\d+))?$/; print(10000 * $1 + 100 * $2 + ($3 == 0 ? $5 != 1 : $3))')
           echo "HCNUMVER=$HCNUMVER" >> "$GITHUB_ENV"
           echo "ARG_TESTS=--enable-tests" >> "$GITHUB_ENV"
@@ -172,6 +176,8 @@ jobs:
           echo "packages: $GITHUB_WORKSPACE/source/labs" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/labs/lab1/testsuite" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/labs/lab2/testsuite" >> cabal.project
+          echo "packages: $GITHUB_WORKSPACE/source/labs/lab3/testsuite" >> cabal.project
+          echo "packages: $GITHUB_WORKSPACE/source/labs/lab4/testsuite" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/labs/lab2/haskell" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/labs/lab3/haskell" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/labs/lab4/haskell" >> cabal.project
@@ -192,6 +198,10 @@ jobs:
           echo "PKGDIR_plt_test_lab1=${PKGDIR_plt_test_lab1}" >> "$GITHUB_ENV"
           PKGDIR_plt_test_lab2="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/plt-test-lab2-[0-9.]*')"
           echo "PKGDIR_plt_test_lab2=${PKGDIR_plt_test_lab2}" >> "$GITHUB_ENV"
+          PKGDIR_plt_test_lab3="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/plt-test-lab3-[0-9.]*')"
+          echo "PKGDIR_plt_test_lab3=${PKGDIR_plt_test_lab3}" >> "$GITHUB_ENV"
+          PKGDIR_plt_test_lab4="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/plt-test-lab4-[0-9.]*')"
+          echo "PKGDIR_plt_test_lab4=${PKGDIR_plt_test_lab4}" >> "$GITHUB_ENV"
           PKGDIR_lab2="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/lab2-[0-9.]*')"
           echo "PKGDIR_lab2=${PKGDIR_lab2}" >> "$GITHUB_ENV"
           PKGDIR_lab3="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/lab3-[0-9.]*')"
@@ -204,6 +214,8 @@ jobs:
           echo "packages: ${PKGDIR_plt_run_java_lab}" >> cabal.project
           echo "packages: ${PKGDIR_plt_test_lab1}" >> cabal.project
           echo "packages: ${PKGDIR_plt_test_lab2}" >> cabal.project
+          echo "packages: ${PKGDIR_plt_test_lab3}" >> cabal.project
+          echo "packages: ${PKGDIR_plt_test_lab4}" >> cabal.project
           echo "packages: ${PKGDIR_lab2}" >> cabal.project
           echo "packages: ${PKGDIR_lab3}" >> cabal.project
           echo "packages: ${PKGDIR_lab4}" >> cabal.project
@@ -213,6 +225,10 @@ jobs:
           echo "    ghc-options: -Werror=missing-methods" >> cabal.project
           echo "package plt-test-lab2" >> cabal.project
           echo "    ghc-options: -Werror=missing-methods" >> cabal.project
+          echo "package plt-test-lab3" >> cabal.project
+          echo "    ghc-options: -Werror=missing-methods" >> cabal.project
+          echo "package plt-test-lab4" >> cabal.project
+          echo "    ghc-options: -Werror=missing-methods" >> cabal.project
           echo "package lab2" >> cabal.project
           echo "    ghc-options: -Werror=missing-methods" >> cabal.project
           echo "package lab3" >> cabal.project
@@ -221,7 +237,7 @@ jobs:
           echo "    ghc-options: -Werror=missing-methods" >> cabal.project
           cat >> cabal.project <<EOF
           EOF
-          $HCPKG list --simple-output --names-only | perl -ne 'for (split /\s+/) { print "constraints: $_ installed\n" unless /^(lab2|lab3|lab4|plt-run-java-lab|plt-test-lab1|plt-test-lab2)$/; }' >> cabal.project.local
+          $HCPKG list --simple-output --names-only | perl -ne 'for (split /\s+/) { print "constraints: any.$_ installed\n" unless /^(lab2|lab3|lab4|plt-run-java-lab|plt-test-lab1|plt-test-lab2|plt-test-lab3|plt-test-lab4)$/; }' >> cabal.project.local
           cat cabal.project
           cat cabal.project.local
       - name: dump install plan
@@ -229,7 +245,7 @@ jobs:
           $CABAL v2-build $ARG_COMPILER $ARG_TESTS $ARG_BENCH --dry-run all
           cabal-plan
       - name: restore cache
-        uses: actions/cache/restore@v3
+        uses: actions/cache/restore@v4
         with:
           key: ${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
           path: ~/.cabal/store
@@ -252,7 +268,7 @@ jobs:
           rm -f cabal.project.local
           $CABAL v2-build $ARG_COMPILER --disable-tests --disable-benchmarks all
       - name: save cache
-        uses: actions/cache/save@v3
+        uses: actions/cache/save@v4
         if: always()
         with:
           key: ${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
